### ISSUE TITLE
Issue with FPS mistake in the article

### ISSUE THREAD

**Issue by hankplease** [datvuthanh/HybridNets#58]
Hello. First of all,thank you for this work.

I noted you mistake the code about the inf_time and fps.

So I think maybe you  calculation the inference time incorrectly in the article , your article show that YOLOP  have 52ms the infercence time per frame(batch size 1), which mean 20fps? (although 41 fps show in the YOLOP's article).

And sadly in the hybridnets_test.py , i try calculate the HYBRIDNET's inference time but only get 0.06s(only model(x) ) ,which means 17-20fps. （Tesla v100 ）but get 0.021s(only model(x) ) in YOLOP, which means 48 fps（Tesla v100 ）

Sadly , it may not faster than YOLOP and not reach the real-time.

**Comment by xoiga123** [comment]
The correct result from our paper is from `hybridnets_test.py`, while that bug is from `hybridnets_test_videos.py`. Sorry for the confusion.

Can you provide us with your exact benchmark configuration (cuda, cudnn)? We rented a V100 instance on [vast.ai](https://vast.ai/) and did our benchmark there, maybe it had something to do with cuda optimization? As referenced in [this comment](https://github.com/datvuthanh/HybridNets/issues/54#issuecomment-1200662656), on newer GPUs (or cuda), YOLOP runs faster than us on pure pytorch.

**Comment by bigsquirrel18** [comment]
Maybe you can enhance inference speed by setting `cudnn.benchmark = False` in line 69 in `hybridnets_test.py`. After I applied that change, the inference time reduced from 0.050s to 0.353s (batch size 1).

**Comment by datvuthanh** [comment]
If you don't have question anymore, i'll close this issue.
